### ISSUE TITLE
Region Portability Issue

### ISSUE THREAD

**Issue by kennschr** [aws-samples/aws-vpc-builder-cdk#2]
Trying to get vpc builder running in a different region is not that straight forward. Tried to stand-up in us-west-2 with global: global:
  # ** Replace with overall organizational ID **
  # Uncomment below  if you'd like to use RAM Sharing
  organizationId: o-hjw5j8o5mo
  stackNamePrefix: sample-complex
  ssmPrefix: /sample-complex/network
  region: us-west-2
  availabilityZones:
    - us-west-2a
    - us-west-2b

This leads to error with: 
Endpoint vpc-endpoints: Service interface file sample-complex-endpoints-us-west-2.txt not found in the config directory

After creating the interface endpoint file it was looking for based on the us-east-1.txt reference and updating to us-west-2 values I'm still getting endpoint erorrs:
Error: Interface Endpoint named  not found in discovery files
    at VpcInterfaceEndpointsStack.lookupPrivateDnsName (/Users/kennschr/IAC/CDK/aws-vpc-builder-cdk/lib/vpc-interface-endpoints-stack.ts:198:13)
    at /Users/kennschr/IAC/CDK/aws-vpc-builder-cdk/lib/vpc-interface-endpoints-stack.ts:105:43
    at Array.forEach (<anonymous>)
    at new VpcInterfaceEndpointsStack (/Users/kennschr/IAC/CDK/aws-vpc-builder-cdk/lib/vpc-interface-endpoints-stack.ts:75:25)
    at StackMapper.providerEndpointStacks (/Users/kennschr/IAC/CDK/aws-vpc-builder-cdk/lib/stack-mapper.ts:151:26)
    at StackBuilderClass.createEndpointServiceInterfaceStack (/Users/kennschr/IAC/CDK/aws-vpc-builder-cdk/lib/stack-builder.ts:365:37)
    at StackBuilderClass.buildEndpointStacks (/Users/kennschr/IAC/CDK/aws-vpc-builder-cdk/lib/stack-builder.ts:334:20)
    at StackBuilderClass.build (/Users/kennschr/IAC/CDK/aws-vpc-builder-cdk/lib/stack-builder.ts:128:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /Users/kennschr/IAC/CDK/aws-vpc-builder-cdk/bin/vpc-builder.ts:15:7

**Comment by apmclean** [comment]
Hey Ken, thanks for kicking the tires!

Can you include the contents of the `sample-complex-endpoints-us-west-2.txt` file you created?  It looks to me like I've interpreted a blank line as an endpoint given the error you're seeing `Error: Interface Endpoint named not found in discovery files`.  Does that file have empty lines?

Point taken that multi-region should be easier to implement.  Endpoints are actually a little tricky since coverage is not uniform between regions and AZs.  ie: an endpoint could exist in AZ1, and AZ2, but not AZ3.  The code actually detects that scenario based on discovery files in the `discovery/` folder in the project.  That discovery information is populated by code in the `/tools` folder if you're interested in unpacking that.

**Comment by kennschr** [comment]
[sample-complex-endpoints-us-west-2.txt](https://github.com/aws-samples/aws-vpc-builder-cdk/files/9962046/sample-complex-endpoints-us-west-2.txt)
Attached my config/sample-complex-endpoints-us-west-2.txt 

There does not seem to be any empty lines.

I've been exploring all the various folders in the project but this is my first real attempt at using CDK beyond the primer and need to learn Typescript here so slow going at the moment.

**Comment by apmclean** [comment]
Your file has a newline at the end.  That's totally fine but my parsing doesn't handle it well.  I'll add some code to detect and filter it out.  In the meantime you can use this file (which has the newline at the end of the file removed) so you can continue!

[sample-complex-endpoints-us-west-2.txt](https://github.com/aws-samples/aws-vpc-builder-cdk/files/9972029/sample-complex-endpoints-us-west-2.txt)

**Comment by apmclean** [comment]
Created #3 and #4
